[Object]
; This is the name of the object in the FITS headers
name                = ALTAIR
# Observation start time for the data set
start_time          = 06:25:00
# Observation end time for the data set
; end_time            = 20240917:06:33:00
end_time            = 06:33:00




[FP]
# Directory where the focal plane telemetry files are located
tel_dir             = /media/arcadia/FASTDAT/data/Altair/FP/raw_frames_cropped
# Directory where the FP images are located
image_dir           = /media/arcadia/FASTDAT/data/Altair/FP/raw_frames_cropped
# Time offset to apply to FP telemetry (in seconds)
# i.e. a frame_offset = 3 means the focal plane images are 3 seconds ahead of
# the PL spectra. See function find_overlap() in d_synchronize.py
time_offset         = 0.0
# Where to save the synchronized FP images
synced_dir          = /media/arcadia/FASTDAT/data/Altair/PL/synced_FP




[PL]
# Directory where the photonic lantern telemetry files are located
tel_dir             = /media/arcadia/FASTDAT/data/Altair/PL/raw_frames
# Directory where the PL images are located
image_dir           = /media/arcadia/FASTDAT/data/Altair/PL/raw_frames




[Plotting]
# Directory where to save the plots
plot_dir            = /media/arcadia/FASTDAT/data/Altair/PL/plots/seb_extraction_vampires