[Object]
; This is the name of the object in the FITS headers
name                = ALTAIR
# Observation start time for the data set
start_time          = 06:25:00
# Observation end time for the data set
end_time            = 06:33:00




[FP]; i.e. "focal plane". But generically this is the fast camera
# Directory where the focal plane telemetry files are located
tel_dir             = /directory/containing/txt/telemetry/files
# Directory where the FP images are located
image_dir           = /directory/containing/image/datacubes
# Time offset to apply to FP telemetry (in seconds)
# i.e. a frame_offset = 3 means the focal plane images are 3 seconds ahead of
# the PL spectra. See function find_overlap() in d_synchronize.py
time_offset         = 0.0
# Where to save the synchronized FP images
synced_dir          = /directory/where/synchronized/images/should/be/saved




[PL] ; i.e. "photonic lantern". But generically this is the slow camera
# Directory where the photonic lantern telemetry files are located
tel_dir             = /directory/containing/txt/telemetry/files
# Directory where the PL images are located
image_dir           = /directory/containing/image/datacubes


